name: "'Stale Issue Cleanup' Action for GitHub Actions"
description: 'Close issues and pull requests with no recent activity'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  stale-issue-message:
    description: 'The message to post on the issue when tagging it. If none provided, will not mark issues stale.'
  stale-pr-message:
    description: 'The message to post on the pr when tagging it. If none provided, will not mark pull requests stale.'
  days-before-stale:
    description: 'The number of days old an issue can be before marking it stale'
    default: 60
  days-before-close:
    description: 'The number of days to wait to close an issue or pull request after it being marked stale'
    default: 7
  stale-issue-label:
    description: 'The label to apply when an issue is stale'
    default: 'Stale'
  exempt-issue-label:
    description: 'The label to apply when an issue is exempt from being marked stale'
  stale-pr-label:
    description: 'The label to apply when a pull request is stale'
    default: 'Stale'
  exempt-pr-label:
    description: 'The label to apply when a pull request is exempt from being marked stale'
  ancient-issue-message:
    description: 'The label to apply when an issue is very old'
  ancient-pr-message:
    description: 'The label to apply when a pr is very old'
  days-before-ancient:
    description: 'The number of days old an issue can be before marking it ancient'
    default: 360
  response-requested-label:
    description: 'The label that gets applied when a response is requested'
  closed-for-staleness-label:
    description: 'The label that gets applied when an issue is closed for staleness'
  minimum-upvotes-to-exempt:
    description: 'The minimum number of "upvotes" that an issue needs to have before not marking as ancient'
  loglevel:
    description: 'Set to DEBUG to enable debug logging'
  dry-run:
    description: 'Set to true to not perform repository changes'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO_TOKEN: ${{ inputs.repo-token }}
    ANCIENT_ISSUE_MESSAGE: ${{ inputs.ancient-issue-message }}
    ANCIENT_PR_MESSAGE: ${{ inputs.ancient-pr-message }}
    STALE_ISSUE_MESSAGE: ${{ inputs.stale-issue-message }}
    STALE_PR_MESSAGE: ${{ inputs.stale-pr-message }}
    DAYS_BEFORE_STALE: ${{ inputs.days-before-stale }}
    DAYS_BEFORE_CLOSE: ${{ inputs.days-before-close }}
    DAYS_BEFORE_ANCIENT: ${{ inputs.days-before-ancient }}
    STALE_ISSUE_LABEL: ${{ inputs.stale-issue-label }}
    EXEMPT_ISSUE_LABEL: ${{ inputs.exempt-issue-label }}
    STALE_PR_LABEL: ${{ inputs.stale-pr-label }}
    EXEMPT_PR_LABEL: ${{ inputs.exempt-pr-label }}
    RESPONSE_REQUESTED_LABEL: ${{ inputs.response-requested-label }}
    CFS_LABEL: ${{ inputs.closed-for-staleness-label }}
    MINIMUM_UPVOTES_TO_EXEMPT: ${{ inputs.minimum-upvotes-to-exempt }}
    LOGLEVEL: ${{ inputs.loglevel }}
    DRYRUN: ${{ inputs.dry-run }}
